<div class="container">
    <div class="row">
        <div class="col-md-7 col-md-offset-2">
            <h2>MONAD Builder</h2>
            <hr/>
            <div class="form-group">
                <input type="text" class="form-control input-lg" name="img"  placeholder="Image URL">
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <input type="number" name="x1"class="form-control input-lg" placeholder="0">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <input type="number" name="y1"class="form-control input-lg" placeholder="0">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <input type="number" name="x2"class="form-control input-lg" placeholder="0">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <input type="number" name="y2"class="form-control input-lg" placeholder="0">
                    </div>
                </div>
            </div>

            <img src="" id="monadImg" />
            <hr class="colorgraph">
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-success btn-block btn-lg">Save</button>
                </div>
            </div>
            <p><hr/></p>
        </div>
    </div>
</div>

<script src="/js/monad.js"></script>
<script src="/js/builder.js"></script>
