<div class="container">
    <div class="row">
        <div class="col-md-7 col-md-offset-2">
            <form role="form">
                <h2>Please Sign Up
                    <small>It's free and always will be.</small>
                </h2>
                <hr/>
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="text" name="first_name" id="first_name" class="form-control input-lg"
                                   placeholder="First Name" tabindex="1">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="text" name="last_name" id="last_name" class="form-control input-lg"
                                   placeholder="Last Name" tabindex="2">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" name="display_name" id="display_name" class="form-control input-lg"
                           placeholder="Display Name" tabindex="3">
                </div>
                <div class="form-group">
                    <input type="email" name="email" id="email" class="form-control input-lg"
                           placeholder="Email Address" tabindex="4">
                </div>
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="password" name="password" id="password" class="form-control input-lg"
                                   placeholder="Password" tabindex="5">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="password" name="password_confirmation" id="password_confirmation"
                                   class="form-control input-lg" placeholder="Confirm Password" tabindex="6">
                        </div>
                    </div>
                </div>

                <div data-monad></div>

                <hr class="colorgraph">
                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-block btn-lg">Register</button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-info btn-block btn-lg">Sign In</button>
                    </div>
                </div>
                <p><hr/></p>
            </form>
        </div>
    </div>
</div>
<script src="/js/monad.app.js"></script>
